// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC15SukXZ4zyoix2mA2ezm1gOqJ4Aw5hJY',
    appId: '1:1059732164627:web:eea63dbdc19e015cd9efe6',
    messagingSenderId: '1059732164627',
    projectId: 'ecommerce-app-kl2025',
    authDomain: 'ecommerce-app-kl2025.firebaseapp.com',
    storageBucket: 'ecommerce-app-kl2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7v5oFxCLO6DKXLNqAuyyIeOcqsQ3jnh8',
    appId: '1:1059732164627:android:ec56ad451425b7f0d9efe6',
    messagingSenderId: '1059732164627',
    projectId: 'ecommerce-app-kl2025',
    storageBucket: 'ecommerce-app-kl2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuBw2UT733i8P7mnNKwbc28kH7kyjAx14',
    appId: '1:1059732164627:ios:bcfacac43761ccc7d9efe6',
    messagingSenderId: '1059732164627',
    projectId: 'ecommerce-app-kl2025',
    storageBucket: 'ecommerce-app-kl2025.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuBw2UT733i8P7mnNKwbc28kH7kyjAx14',
    appId: '1:1059732164627:ios:bcfacac43761ccc7d9efe6',
    messagingSenderId: '1059732164627',
    projectId: 'ecommerce-app-kl2025',
    storageBucket: 'ecommerce-app-kl2025.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC15SukXZ4zyoix2mA2ezm1gOqJ4Aw5hJY',
    appId: '1:1059732164627:web:746101cdbd0165e2d9efe6',
    messagingSenderId: '1059732164627',
    projectId: 'ecommerce-app-kl2025',
    authDomain: 'ecommerce-app-kl2025.firebaseapp.com',
    storageBucket: 'ecommerce-app-kl2025.firebasestorage.app',
  );

}